skumarscse-skillsafari/hitech

src/App.tsx
=> app.tsx conflict fixed

package-lock.json, package.json, src/App.tsx
=> slick added

src/components/LocationMap.tsx, src/components/NewsEventsSection.tsx, src/data/contactData.json
changed mail in footer as [hit.office@hindusthan.net]
in featured news removed icons
=> modified old changes

src/pages/HomePage.tsx
Create a about as page in home
=> created abouts page

src/components/FacultyCarousel.tsx, src/components/FacultyModal.tsx, src/data/departmentsData.json
added publications and patents in faculty
small small animation edits in meet our faculty section
=> added publications and patents in faculty

src/components/FacultyCarousel.tsx, src/components/FacultyModal.tsx, src/data/departmentsData.json
Reverts skumarscse-skillsafari/hitech#17
=> Revert "added publications and patents in faculty"

src/App.tsx, src/components/About.tsx, src/components/Footer.tsx, src/components/Header.tsx, src/components/NewsTicker.tsx, src/components/SocialMediaCarousel.tsx, src/components/TopNavBar.tsx, src/data/departmentsData.json, src/data/headerData.json, src/index.css, src/pages/BoardOfGovernance.tsx, src/pages/DepartmentPage.tsx, src/pages/HomePage.tsx, src/pages/PrincipalsDesk.tsx
Reverts skumarscse-skillsafari/hitech#18
=> Revert "principal's desk, added facilities in navbar,removed scrollbar,update…"

src/components/AccreditationCards.tsx, src/data/newsTickerData.json, src/pages/ObeInputs.tsx
changed button size in accredation cards
and changed size in obe inputs box
=> small changes

src/components/Header.tsx
=> added opotions in hamburger

src/components/Hero.tsx, src/components/TabSection.tsx, src/data/newsTickerData.json
edited on hero.tsx,newsticker.tsx
=> edited on hero.tsx,newsticker.tsx

src/components/ReusableTable.tsx
=> addded tabs in table

src/components/TeachingMethodologyCards.tsx, src/pages/InnovativeMethods.tsx, src/pages/PrincipalsDesk.tsx, src/pages/objectives.tsx
=> back button

src/components/ReusableTable.tsx, src/components/TabSection.tsx
styled tables and removed frame for hod photo in tabsection
=> worked on reusabledatatable.tsx and tabsection.tsx

src/App.tsx
added incubatoin lab and gallery page
=> added incubation lab and gallery page

package-lock.json, package.json, src/components/AccreditationCards.tsx, src/components/Admissions.tsx, src/components/Hero.tsx, src/pages/ControllerOfExaminationsPage.tsx, src/pages/HomePage.tsx, src/pages/InnovativeMethods.tsx, tailwind.config.js
edited in title,ranking cards,added animation to welcome to hitech and small changes
=> small changes in homepage

src/components/FacultyCarousel.tsx, src/components/LabCard.tsx, src/components/LabSection.tsx, src/components/TabSection.tsx, src/data/galleryData.json, src/data/labs/cseLabs.json, src/data/tabsData.json, src/pages/DepartmentPage.tsx
small changes in labsection (dept page) and tabsection
=> small changes and worked in tabsection

src/components/ReusableTable.tsx, src/data/SecData.json, src/pages/DataTable.tsx
=> new updates

src/components/ReusableTable.tsx, src/components/TabSection.tsx, src/data/SecData.json, src/pages/DataTable.tsx
made tables reponsive and kept the academic year drop down on above table
=> tabsection tables

src/components/ReusableTable.tsx, src/data/SecData.json
Added data in research and development
=> added data in research and development

src/data/SecData.json
added in international Journals
=> added in international Journals

src/components/ReusableTable.tsx, src/pages/AcademicCal.tsx, src/pages/DepartmentPage.tsx, src/pages/MagazinePage.tsx, src/pages/NewsLetterPage.tsx
animated the quick links button in departments page
=> worked in magazine and newsletter page

src/App.tsx, src/components/Admissions.tsx, src/components/Library.tsx, src/data/SecData.json, src/pages/Management.tsx
=> small edits
